### ISSUE TITLE
Confusing behaviour when placing two 2-wide doors side by side

### ISSUE THREAD

**Issue by fluxionary** [oversword/bigdoors#10]
![image](https://user-images.githubusercontent.com/25628292/106528641-efc15500-649d-11eb-8065-b138b19c090a.png)

If you place then on top of blocks like the following, the 2nd door will be properly mirrored:
* L__R (left pair in picture)

However, if you place then as follows, you'll get two left-hand doors:
* L_R_ (right pair in picture)

**Comment by oversword** [comment]
I am not seeing this, can you give better instructions on how to replicate?

I have a feeling you must've placed the right hand door first, or the left-hand door is actually an open variant of the right-hand door.

The algorithm does not consider the blocks below the doors at any stage, so this seems impossible.

**Comment by fluxionary** [comment]
It's not so much about what the blocks below are, but what i'm aiming at when i place the door. Let me try to figure out how to record a video

**Comment by oversword** [comment]
Oh because you're aiming at the other door? I don't think that can be fixed easily, the node you are placing it at will always be where the bottom left of the door will go (bottom right if flipped)

**Comment by fluxionary** [comment]
i can't figure out how to get video recording to go rn.

imagine 4 pieces of sand, laying on the ground in a line. it doesn't have to be sand, that's just an example.
```
(sand) (sand) (sand) (sand)
```

they're in a big flat plain, so there's room for the doors. 

if i place a door on the first sand (from left to right), and then on the third sand, i'll get two left-handed doors. if i place the second door on the fourth sand, though, it'll transform into a right-handed door. 

It should also transform into a right-handed door, in the other case.

**Comment by oversword** [comment]
Gotcha, sorry that's a "won't do", the pairing logic is complex enough as it is.

**Comment by fluxionary** [comment]
Sounds good. We just have to make sure people know how to make it work as it does now.
