### ISSUE TITLE
Big doors should send player a notification if there isn't enough room to build the door

### ISSUE THREAD

**Issue by fluxionary** [oversword/bigdoors#12]
In particular, it should remind them to make sure the area occupied by the "open" door is also clear.

**Comment by oversword** [comment]
@fluxionary 
I decided to use the hud notification copied (almost) directly from the rhotator mod. This is how user notifications SHOULD be done in my opinion

Check out this file for a basic implementation, it may be useful in the future for other mods (smart shops for instance):
https://github.com/oversword/bigdoors/pull/17/files#diff-86ae8b373bf50952127569b8d4139f3c78d980dd69128394ca324f2ec6c09c6b

It could probably be a bit cleaner but it works
