### ISSUE TITLE
add setting to force "replace_original" for all registered bigdoors

### ISSUE THREAD

**Issue by fluxionary** [oversword/bigdoors#18]
I want to make sure all doors do this by default.

**Comment by fluxionary** [comment]
I want to make sure all doors do this by default.

**Comment by oversword** [comment]
I will probably allow you to set an entire default config so I don't have to do a custom change for each option

**Comment by oversword** [comment]
`minetest.register_alias` does not seem to be doing anything useful.

Are you sure you want to register an lbm one the server? I can put in an option to turn that off separately from the other replace_original functions, I'm not sure we should be switching that on until we're 100% sure we want it

**Comment by oversword** [comment]
Ahh wait, `_force` seems to do the trick

**Comment by fluxionary** [comment]
use `register_alias_force`

**Comment by oversword** [comment]
Check out [config.lua](https://github.com/oversword/bigdoors/pull/19/files#diff-437dcbdcefbb257379ec6d95c6877f5f4feb823b3c5d920b643f9aeebcad7db0) for default / example config

But TBH you probably just need to know to set `bigdoors.replace_original = true` in the conf
