### ISSUE TITLE
Closed default doors become unknown nodes

### ISSUE THREAD

**Issue by fluxionary** [oversword/bigdoors#28]
After installing bigdoors and setting `bigdoors.replace_original = true`

Open doors seem to be fine. 

![screenshot_20210215_140141](https://user-images.githubusercontent.com/25628292/107997063-c53fc380-6f96-11eb-83c5-d7c217edf391.png)
![screenshot_20210215_140145](https://user-images.githubusercontent.com/25628292/107997082-cc66d180-6f96-11eb-9327-bd0ee872f66e.png)

**Comment by oversword** [comment]
I can't reproduce this, can you give stepwise instructions from a fresh world?

**Comment by oversword** [comment]
Can I also see that error log? Did that happen when you used the node inspector or as the world loaded?

**Comment by oversword** [comment]
It looks like homedecor is also messing with doors, if this mod and homedecor are both enabled this issue occurs

**Comment by oversword** [comment]
So final verdict: homedecor_3d_extras is overriding the two closed door meshes, and re-asserting the old door name while it's at it. The solution is to optionally depend on this mod to make sure we are loaded after it and our overrides are final
