### ISSUE TITLE
Mesecons compatability: opening/closing

### ISSUE THREAD

**Issue by fluxionary** [oversword/bigdoors#4]
Mesecons should be an optional dependency. 

Doors need to open when receiving a mesecons "on" signal, and close when they receive a mesecons "close" signal, otherwise they won't work w/ e.g. pressure plates

**Comment by oversword** [comment]
Unfortunately this isn't perfect, I tried sending mesecons diagonally but it won't do it. This may mean some awkward setups for 2-wide doors
