### ISSUE TITLE
Mesecons compatability: MVPS stoppers

### ISSUE THREAD

**Issue by fluxionary** [oversword/bigdoors#5]
All door nodes (including the hidden ones) should be registered as MVPS stoppers, because MVPS doesn't behave well w/ multi-node blocks. 

I've just noticed that other doors aren't MVPS stoppers either, which makes problems, I'll have to fix that in `bls_custom`. It'd be easier for me if you ensure that anything registered w/ `big_doors` automatically gets made an MVPS stopper.

Aside: mesecons actually tries to make steel doors MVPS stoppers, but for a really old version of minetest_game that has no effect now :\

**Comment by fluxionary** [comment]
![image](https://user-images.githubusercontent.com/25628292/106527428-1e3e3080-649c-11eb-97f6-501bf8aff96c.png)

**Comment by oversword** [comment]
Yeah I meant to do this, sorry 👍
