### ISSUE TITLE
Why is there a 1x2 door

### ISSUE THREAD

**Issue by fluxionary** [oversword/bigdoors#8]
This seems to just be a duplicate of the standard door, except it can't be used to make larger doors :\

**Comment by oversword** [comment]
Regular doors will not pair with bigdoors, I want to introduce an option to exclude this door for those who don't want it, there is already the option to replace the original door with the 1x2 bigdoor, but that introduces an lbm and shouldn't be done by default.

If you want this option I will need to remove `default-doors.lua` and have you register them in a custom manner inside bls_custom

**Comment by fluxionary** [comment]
Oh, if that's the case, maybe alias the original doors to the big doors variant?

**Comment by oversword** [comment]
That's effectively what the `replace_original` option does.

Also note "it can't be used to make larger doors" is related to #7 and fixed by #15

**Comment by fluxionary** [comment]
oh sorry, i missed the options. we'll be using that then.

**Comment by oversword** [comment]
Let me check if "making an alias" makes registering an lmb pointless, and make `default-doors.lua` more of an example rather than a default before putting this on the server, this will also be paired with a change to bls_custom

**Comment by oversword** [comment]
Seen your new issue 👍 
related to #18
